#version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" 
    env_file: .env  # contains DB URL, SUPABASE_KEY, etc.

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      API_BASE_URL: http://backend:8000
      LOAD_API_KEY: ${LOAD_API_KEY}
